# -*- MakeFile -*-
#
# Written by Simon Rydell
# April 2018
#

.PHONY: all graphFunctions isingWorm plotGraph

all: graphFunctions isingWorm plotGraph

graphFunctions:
	python -m unittest test_graphFunctions.py

isingWorm:
	python -m unittest test_isingWorm.py

plotGraph:
	python -m unittest test_plotGraph.py
