# -*- MakeFile -*-
#
# Written by Simon Rydell
# May 2018
#

.PHONY: all
all:
	@./run.sh all

.PHONY: build
build:
	@./run.sh build

.PHONY: i
i:
	@./run.sh i

.PHONY: x
x:
	@./run.sh x

.PHONY: test
test:
	@./run.sh test

